In [1]:
import sys, os, re, csv
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
# CSV の準備
df = pd.read_csv('順番付き.csv',encoding = "shift-jis",index_col=0)

N = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37]
S = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s',
        't','u','v','w','x','y','z','七','八','九','零','一','二','三','四','五','六','末']
dic = dict(zip(N,S))

In [3]:
print(dic)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 27: '七', 28: '八', 29: '九', 30: '零', 31: '一', 32: '二', 33: '三', 34: '四', 35: '五', 36: '六', 37: '末'}

In [4]:
df = df.replace({1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 27: '七', 28: '八', 29: '九', 30: '零', 31: '一', 32: '二', 33: '三', 34: '四', 35: '五', 36: '六', 37: '末'})

In [5]:
df

    1st 2nd 3rd 4th 5th 6th 7th 8th 9th
382   h   e   v   s   c   末   b   p   八
381   七   d   y   h   二   一   z   v   i
380   y   六   n   四   x   h   二   p   m
379   c   九   v   h   x   o   五   r   z
378   n   e   九   i   a   j   o   八   t
..   ..  ..  ..  ..  ..  ..  ..  ..  ..
5     八   d   u   p   a   e   c   一   v
4     八   v   m   九   x   l   w   b   n
3     g   k   h   w   b   一   n   o   e
2     三   x   一   九   五   t   四   二   l
1     j   g   l   q   w   八   四   c   o

[382 rows x 9 columns]

In [26]:
df['1st'] = df['1st'].astype('str').str.zfill(2)
df['2nd'] = df['2nd'].astype('str').str.zfill(2)
df['3rd'] = df['3rd'].astype('str').str.zfill(2)
df['4th'] = df['4th'].astype('str').str.zfill(2)
df['5th'] = df['5th'].astype('str').str.zfill(2)
df['6th'] = df['6th'].astype('str').str.zfill(2)
df['7th'] = df['7th'].astype('str').str.zfill(2)

In [6]:
df = df.iloc[::-1]

In [7]:
df

    1st 2nd 3rd 4th 5th 6th 7th 8th 9th
1     j   g   l   q   w   八   四   c   o
2     三   x   一   九   五   t   四   二   l
3     g   k   h   w   b   一   n   o   e
4     八   v   m   九   x   l   w   b   n
5     八   d   u   p   a   e   c   一   v
..   ..  ..  ..  ..  ..  ..  ..  ..  ..
378   n   e   九   i   a   j   o   八   t
379   c   九   v   h   x   o   五   r   z
380   y   六   n   四   x   h   二   p   m
381   七   d   y   h   二   一   z   v   i
382   h   e   v   s   c   末   b   p   八

[382 rows x 9 columns]

In [8]:
df.to_csv('after.csv',encoding='cp932' )